# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0e333306c136f9c9a94d96b420901ccff293ebd83e5f5a1d325978e07fcdbbcf3d46d9339947414500032187a925c5fdf89b3efd82e11267705b3c297a67133

test:
  secret_key_base: 8d4d0cb6950638a0f1855df9dcb0c770806909458a810916518d04c0056e4815c733ed1626ba4b1f1d8ddabbd404fc10895a945ab60aa29b5e977b0f2eb90447

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
